# Generated by Django 4.1.3 on 2023-05-09 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id_comuna', models.BigAutoField(primary_key=True, serialize=False)),
                ('comuna', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id_permiso', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_permiso', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(max_length=30)),
                ('fk_id_permiso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.permiso')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(max_length=50)),
                ('apellido_usuario', models.CharField(max_length=50)),
                ('celular', models.IntegerField()),
                ('correo', models.CharField(max_length=200)),
                ('clave', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('fk_id_comuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.comuna')),
                ('fk_id_rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.rol')),
            ],
        ),
    ]
